### PR TITLE
feat(dev): add watchtower service

### PR DESCRIPTION
**Pull request by pierreboissinot**
This service was removed by 2abf6cdb5db8fb810fe1ef964a0641b7e53d0864

### CODE REVIEW

**Comment by aegypius** [comment]
This service was removed because of the API call rate-limits of docker hub. Without authentication the rate limit is applied by IP address (and authentication did not work properly) which can be easily reached in an enterprise network.

I do not recommend putting it back as a default. 


Le 27 mai 2024 18:04:21 GMT+02:00, Pierre Boissinot ***@***.***> a écrit :

**Comment by pierreboissinot** [comment]
> This service was removed because of the API call rate-limits of docker hub. Without authentication the rate limit is applied by IP address (and authentication did not work properly) which can be easily reached in an enterprise network.
> 
> 
> 
> I do not recommend putting it back as a default. 
> 
> 
> 
> 
> 
> Le 27 mai 2024 18:04:21 GMT+02:00, Pierre Boissinot ***@***.***> a écrit :
> 
> >This service was removed by 2abf6cdb5db8fb810fe1ef964a0641b7e53d0864
> 
> >You can view, comment on, or merge this pull request online at:
> 
> >
> 
> >  https://github.com/le-phare/docker-stack/pull/27
> 
> >
> 
> >-- Commit Summary --
> 
> >
> 
> >  * feat(dev): add watchtower service
> 
> >
> 
> >-- File Changes --
> 
> >
> 
> >    M docker-compose.yml (9)
> 
> >
> 
> >-- Patch Links --
> 
> >
> 
> >https://github.com/le-phare/docker-stack/pull/27.patch
> 
> >https://github.com/le-phare/docker-stack/pull/27.diff
> 
> >
> 
> >-- 
> 
> >Reply to this email directly or view it on GitHub:
> 
> >https://github.com/le-phare/docker-stack/pull/27
> 
> >You are receiving this because you are subscribed to this thread.
> 
> >
> 
> >Message ID: ***@***.***&gt;
> 
> 

Ok thx @aegypius

**Comment by thislg** [comment]
Docker Hub rate limits for anonymous users are 100 pulls per 6 hours per IP address which would we problematic even if we configured it to run once a day. With a free account it becomes a non-issue with 200 pulls per 6 hour period per account. So I think we can put an optional Watchtower service in docker-stack: users would need to enable it in their .env file manually. For rate limit issues we could add a part about creating a Docker Hub account in our documentation.

**Comment by thislg** [comment]
Closes in favor of https://github.com/le-phare/docker-stack/pull/28

**Pull request closed without merging**
